all:
	gcc mongo.c -I/usr/local/include/libmongoc-1.0/ -I/usr/local/include/libbson-1.0  -lmongoc -lbson
update:
	gcc update.c -I/usr/local/include/libmongoc-1.0/ -I/usr/local/include/libbson-1.0  -lmongoc -lbson
find:
	gcc find.c -I/usr/local/include/libmongoc-1.0/ -I/usr/local/include/libbson-1.0  -lmongoc -lbson

